"""Add name column to class

Revision ID: ce0a4552e68b
Revises: 
Create Date: 2024-08-26 11:04:57.619483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0a4552e68b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('professor_id')
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('professor_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['professor_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
